---
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy3"
  - "nightly"

install:
  - pip install -U pip
  - pip install -U wheel setuptools pbr
  - pip install -U .[docs,test]
  - pip list
  - python --version

script:
  - make check
  - rst2html.py README README.html
